# Name: Kshirsagar Vaishnavi Anil

# Roll No.: TCOD73

# Batch: T12

In [3]:
import pandas as pd
df = pd.read_csv("test.csv")
df

,Squad,# Pl,Age,Poss,MP,Starts,Min,90s,Gls,Ast,...,Gls90,Ast90,G+A90,G-PK90,G+A-PK90,xG90,xAG90,xG+xAG90,npxG90,npxG+xAG90
0,Argentina,24,27.5,57.4,7,77,690,7.7,15,8,...,1.96,1.04,3.00,1.43,2.48,1.96,1.00,2.97,1.47,2.48
1,Australia,20,27.8,37.8,4,44,360,4.0,3,3,...,0.75,0.75,1.50,0.75,1.50,0.58,0.48,1.06,0.58,1.06
2,Belgium,20,29.7,57.0,3,33,270,3.0,1,1,...,0.33,0.33,0.67,0.33,0.67,1.57,1.27,2.85,1.57,2.85
3,Brazil,26,27.6,56.2,5,55,480,5.3,8,6,...,1.50,1.13,2.62,1.31,2.44,2.24,1.54,3.79,2.09,3.64
4,Cameroon,22,27.2,41.7,3,33,270,3.0,4,4,...,1.33,1.33,2.67,1.33,2.67,1.14,0.66,1.80,1.14,1.80
5,Canada,19,27.3,52.0,3,33,270,3.0,1,1,...,0.33,0.33,0.67,0.33,0.67,1.41,0.95,2.35,1.18,2.13
6,Costa Rica,22,29.7,31.3,3,33,270,3.0,3,1,...,1.00,0.33,1.33,1.00,1.33,0.48,0.20,0.68,0.48,0.68
7,Croatia,21,28.3,54.3,7,77,690,7.7,8,8,...,1.04,1.04,2.09,1.04,2.09,0.91,0.74,1.65,0.91,1.65
8,Denmark,20,26.6,60.0,3,33,270,3.0,1,1,...,0.33,0.33,0.67,0.33,0.67,0.90,0.59,1.49,0.90,1.49
9,Ecuador,18,24.9,53.3,3,33,270,3.0,4,2,...,1.33,0.67,2.00,1.00,1.67,1.24,0.60,1.84,0.98,1.58
10,England,20,26.1,62.8,5,55,450,5.0,13,11,...,2.60,2.20,4.80,2.40,4.60,1.72,1.12,2.83,1.40,2.52
11,France,24,26.3,51.3,7,77,660,7.3,16,12,...,2.18,1.64,3.82,1.91,3.55,1.88,1.40,3.29,1.67,3.07
12,Germany,20,27.3,59.3,3,33,270,3.0,6,5,...,2.00,1.67,3.67,1.67,3.33,3.35,2.50,5.85,3.09,5.59
13,Ghana,20,25.5,42.0,3,33,270,3.0,5,2,...,1.67,0.67,2.33,1.67,2.33,1.38,0.57,1.95,1.13,1.70
14,Iran,21,28.5,36.7,3,33,270,3.0,4,2,...,1.33,0.67,2.00,1.00,1.67,1.07,0.81,1.88,0.94,1.75
15,Japan,22,28.0,35.8,4,44,390,4.3,5,4,...,1.15,0.92,2.08,1.15,2.08,1.15,0.81,1.96,1.15,1.96
16,Korea Republic,21,28.2,48.3,4,44,360,4.0,5,3,...,1.25,0.75,2.00,1.25,2.00,1.14,0.83,1.98,1.14,1.98
17,Mexico,21,28.2,54.0,3,33,270,3.0,2,1,...,0.67,0.33,1.00,0.67,1.00,1.09,0.90,1.99,1.09,1.99
18,Morocco,25,26.3,39.0,7,77,660,7.3,6,4,...,0.82,0.55,1.36,0.82,1.36,0.90,0.63,1.53,0.90,1.53
19,Netherlands,21,26.8,53.0,5,55,480,5.3,10,8,...,1.87,1.50,3.38,1.87,3.38,0.86,0.54,1.41,0.86,1.41
20,Poland,21,27.8,37.3,4,44,360,4.0,3,1,...,0.75,0.25,1.00,0.50,0.75,1.14,0.44,1.58,0.74,1.18
21,Portugal,24,26.9,60.4,5,55,450,5.0,12,10,...,2.40,2.00,4.40,2.00,4.00,1.57,1.05,2.63,1.26,2.31
22,Qatar,20,28.2,43.0,3,33,270,3.0,1,1,...,0.33,0.33,0.67,0.33,0.67,0.47,0.39,0.87,0.47,0.87
23,Saudi Arabia,23,27.3,44.7,3,33,270,3.0,3,2,...,1.00,0.67,1.67,1.00,1.67,0.99,0.47,1.47,0.71,1.18
24,Senegal,20,26.9,44.8,4,44,360,4.0,5,2,...,1.25,0.50,1.75,1.00,1.50,1.13,0.61,1.74,0.93,1.54
25,Serbia,22,26.5,51.3,3,33,270,3.0,5,4,...,1.67,1.33,3.00,1.67,3.00,1.12,0.95,2.07,1.12,2.07
26,Spain,21,25.5,75.8,4,44,390,4.3,9,5,...,2.08,1.15,3.23,1.85,3.00,1.42,0.92,2.34,1.24,2.16
27,Switzerland,24,27.6,49.0,4,44,360,4.0,5,4,...,1.25,1.00,2.25,1.25,2.25,1.37,0.91,2.28,1.37,2.28
28,Tunisia,21,26.9,44.3,3,33,270,3.0,1,1,...,0.33,0.33,0.67,0.33,0.67,0.77,0.64,1.41,0.77,1.41
29,United States,20,24.5,53.0,4,44,360,4.0,3,3,...,0.75,0.75,1.50,0.75,1.50,1.01,0.87,1.89,1.01,1.89
30,Uruguay,19,27.6,48.7,3,33,270,3.0,2,1,...,0.67,0.33,1.00,0.67,1.00,1.23,0.92,2.15,1.23,2.15
31,Wales,18,26.8,46.7,3,33,270,3.0,1,0,...,0.33,0.00,0.33,0.00,0.00,0.91,0.59,1.49,0.65,1.00

In [4]:
df.head()

,Squad,# Pl,Age,Poss,MP,Starts,Min,90s,Gls,Ast,...,Gls90,Ast90,G+A90,G-PK90,G+A-PK90,xG90,xAG90,xG+xAG90,npxG90,npxG+xAG90
0,Argentina,24,27.5,57.4,7,77,690,7.7,15,8,...,1.96,1.04,3.00,1.43,2.48,1.96,1.00,2.97,1.47,2.48
1,Australia,20,27.8,37.8,4,44,360,4.0,3,3,...,0.75,0.75,1.50,0.75,1.50,0.58,0.48,1.06,0.58,1.06
2,Belgium,20,29.7,57.0,3,33,270,3.0,1,1,...,0.33,0.33,0.67,0.33,0.67,1.57,1.27,2.85,1.57,2.85
3,Brazil,26,27.6,56.2,5,55,480,5.3,8,6,...,1.50,1.13,2.62,1.31,2.44,2.24,1.54,3.79,2.09,3.64
4,Cameroon,22,27.2,41.7,3,33,270,3.0,4,4,...,1.33,1.33,2.67,1.33,2.67,1.14,0.66,1.80,1.14,1.80

In [5]:
df.isnull().sum()

Squad         0
# Pl          0
Age           0
Poss          0
MP            0
Starts        0
Min           0
90s           0
Gls           0
Ast           0
G+A           0
G-PK          0
PK            0
PKatt         0
CrdY          0
CrdR          0
xG            0
npxG          0
xAG           0
npxG+xAG      0
PrgC          0
PrgP          0
Gls90         0
Ast90         0
G+A90         0
G-PK90        0
G+A-PK90      0
xG90          0
xAG90         0
xG+xAG90      0
npxG90        0
npxG+xAG90    0
dtype: int64

In [6]:
df.dtypes

Squad          object
# Pl            int64
Age           float64
Poss          float64
MP              int64
Starts          int64
Min             int64
90s           float64
Gls             int64
Ast             int64
G+A             int64
G-PK            int64
PK              int64
PKatt           int64
CrdY            int64
CrdR            int64
xG            float64
npxG          float64
xAG           float64
npxG+xAG      float64
PrgC            int64
PrgP            int64
Gls90         float64
Ast90         float64
G+A90         float64
G-PK90        float64
G+A-PK90      float64
xG90          float64
xAG90         float64
xG+xAG90      float64
npxG90        float64
npxG+xAG90    float64
dtype: object

In [7]:
df['Age'].mean()

27.196875

In [8]:
df.fillna(value=df['Age'].mean(), inplace=True)

In [9]:
df.describe()

,# Pl,Age,Poss,MP,Starts,Min,90s,Gls,Ast,G+A,...,Gls90,Ast90,G+A90,G-PK90,G+A-PK90,xG90,xAG90,xG+xAG90,npxG90,npxG+xAG90
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,...,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000
mean,21.250000,27.196875,49.443750,4.000000,44.000000,369.375000,4.100000,5.312500,3.781250,9.093750,...,1.195312,0.838125,2.035312,1.081562,1.921875,1.253125,0.840625,2.095937,1.130313,1.965625
std,1.951013,1.177609,9.457066,1.344043,14.784473,135.763967,1.506973,4.130434,3.220242,7.248401,...,0.656329,0.544950,1.167589,0.590517,1.107766,0.555689,0.421364,0.960067,0.499274,0.920985
min,18.000000,24.500000,31.300000,3.000000,33.000000,270.000000,3.000000,1.000000,0.000000,1.000000,...,0.330000,0.000000,0.330000,0.000000,0.000000,0.470000,0.200000,0.680000,0.470000,0.680000
25%,20.000000,26.575000,42.750000,3.000000,33.000000,270.000000,3.000000,2.750000,1.000000,3.750000,...,0.730000,0.330000,1.000000,0.670000,1.000000,0.910000,0.590000,1.520000,0.890000,1.470000
50%,21.000000,27.300000,50.150000,3.500000,38.500000,315.000000,3.500000,4.500000,3.000000,7.000000,...,1.200000,0.710000,2.000000,1.000000,1.670000,1.140000,0.810000,1.920000,1.105000,1.845000
75%,22.000000,27.850000,54.775000,4.250000,46.750000,405.000000,4.475000,6.500000,5.000000,11.750000,...,1.670000,1.135000,2.752500,1.490000,2.527500,1.412500,0.950000,2.342500,1.245000,2.190000
max,26.000000,29.700000,75.800000,7.000000,77.000000,690.000000,7.700000,16.000000,12.000000,28.000000,...,2.600000,2.200000,4.800000,2.400000,4.600000,3.350000,2.500000,5.850000,3.090000,5.590000

In [10]:
df['Squad'].unique()

array(['Argentina', 'Australia', 'Belgium', 'Brazil', 'Cameroon',
       'Canada', 'Costa Rica', 'Croatia', 'Denmark', 'Ecuador', 'England',
       'France', 'Germany', 'Ghana', 'Iran', 'Japan', 'Korea Republic',
       'Mexico', 'Morocco', 'Netherlands', 'Poland', 'Portugal', 'Qatar',
       'Saudi Arabia', 'Senegal', 'Serbia', 'Spain', 'Switzerland',
       'Tunisia', 'United States', 'Uruguay', 'Wales'], dtype=object)

In [17]:
from sklearn.preprocessing import OneHotEncoder

In [18]:
enc = OneHotEncoder()

In [22]:
enc_data = pd.DataFrame(enc.fit_transform(df[['Squad', 'Age']]).toarray())

In [23]:
print(enc_data)

     0    1    2    3    4    5    6    7    8    9   ...   41   42   43   44  \
0   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0
1   0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0
2   0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0
3   0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  1.0
4   0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0  0.0
5   0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0  0.0
6   0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0
7   0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0  0.0
8   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  0.0  0.0
9   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0  0.0
10  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0
11  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0
12  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0  0.0
13  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0
14  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0
15  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0
16  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0
17  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0
18  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0
19  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0
20  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0
21  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0
22  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0
23  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0  0.0
24  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0
25  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0
26  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0
27  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  1.0
28  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0
29  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0
30  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  1.0
31  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0

     45   46   47   48   49   50
0   0.0  0.0  0.0  0.0  0.0  0.0
1   1.0  0.0  0.0  0.0  0.0  0.0
2   0.0  0.0  0.0  0.0  0.0  1.0
3   0.0  0.0  0.0  0.0  0.0  0.0
4   0.0  0.0  0.0  0.0  0.0  0.0
5   0.0  0.0  0.0  0.0  0.0  0.0
6   0.0  0.0  0.0  0.0  0.0  1.0
7   0.0  0.0  0.0  1.0  0.0  0.0
8   0.0  0.0  0.0  0.0  0.0  0.0
9   0.0  0.0  0.0  0.0  0.0  0.0
10  0.0  0.0  0.0  0.0  0.0  0.0
11  0.0  0.0  0.0  0.0  0.0  0.0
12  0.0  0.0  0.0  0.0  0.0  0.0
13  0.0  0.0  0.0  0.0  0.0  0.0
14  0.0  0.0  0.0  0.0  1.0  0.0
15  0.0  1.0  0.0  0.0  0.0  0.0
16  0.0  0.0  1.0  0.0  0.0  0.0
17  0.0  0.0  1.0  0.0  0.0  0.0
18  0.0  0.0  0.0  0.0  0.0  0.0
19  0.0  0.0  0.0  0.0  0.0  0.0
20  1.0  0.0  0.0  0.0  0.0  0.0
21  0.0  0.0  0.0  0.0  0.0  0.0
22  0.0  0.0  1.0  0.0  0.0  0.0
23  0.0  0.0  0.0  0.0  0.0  0.0
24  0.0  0.0  0.0  0.0  0.0  0.0
25  0.0  0.0  0.0  0.0  0.0  0.0
26  0.0  0.0  0.0  0.0  0.0  0.0
27  0.0  0.0  0.0  0.0  0.0  0.0
28  0.0  0.0  0.0  0.0  0.0  0.0
29  0.0  0.0  0.0  0.0  0.0  0.0
30  0.0  0.0  0.0  0.0  0.0  0.0
31  0.0  0.0  0.0  0.0  0.0  0.0

[32 rows x 51 columns]

In [24]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['Squad']= label_encoder.fit_transform(df['Squad'])
df['Squad'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [26]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['Age']= label_encoder.fit_transform(df['Age'])
df['Age'].unique()

array([11, 13, 18, 12,  9, 10, 16,  6,  1,  3,  4,  2, 17, 14, 15,  7,  8,
        5,  0], dtype=int64)

In [27]:
df.head()

,Squad,# Pl,Age,Poss,MP,Starts,Min,90s,Gls,Ast,...,Gls90,Ast90,G+A90,G-PK90,G+A-PK90,xG90,xAG90,xG+xAG90,npxG90,npxG+xAG90
0,0,24,11,57.4,7,77,690,7.7,15,8,...,1.96,1.04,3.00,1.43,2.48,1.96,1.00,2.97,1.47,2.48
1,1,20,13,37.8,4,44,360,4.0,3,3,...,0.75,0.75,1.50,0.75,1.50,0.58,0.48,1.06,0.58,1.06
2,2,20,18,57.0,3,33,270,3.0,1,1,...,0.33,0.33,0.67,0.33,0.67,1.57,1.27,2.85,1.57,2.85
3,3,26,12,56.2,5,55,480,5.3,8,6,...,1.50,1.13,2.62,1.31,2.44,2.24,1.54,3.79,2.09,3.64
4,4,22,9,41.7,3,33,270,3.0,4,4,...,1.33,1.33,2.67,1.33,2.67,1.14,0.66,1.80,1.14,1.80